spring:
  application:
    name: cb-sample-foo

server:
  port: 2423

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2421/eureka/
  instance:
    hostname: localhost

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


