
server:
  port: 2422

spring:
  application:
    name: cb-spring-zuul


zuul:
  #Service will be mapped under the /api URI
  ignoredServices: '*'
  prefix: /api
  routes:
    hello-server:
      path: /foo/**
      serviceId: cb-sample-foo
   # hello-client:
      #path: /zoo/**
      #serviceId: HELLO-CLIENT

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2421/eureka/
  instance:
    hostname: localhost

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000